sudo: required
services:
  - docker

before_install:
  - docker build -t SivaprasadTamatam/docker-react -f Dockerfile.dev .

script:
  - docker run SivaprasadTamatam/docker-react npm run test -- --coverage
